name: Run Test Automation
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Covert json to file
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: '{
                "name": "pipelines",
                "activity": 3,
                "module": 2,
                "isRequired": false
              }'
          filename: 'archivo.json'
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: archivo.json
          path: archivo.json